sonar.projectKey=arnabnandy7_api-response-comparator
sonar.organization=arnabnandy7

sonar.sources=src
sonar.tests=test

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.d.ts
